const colors = ['red', 'white', 'blue'];
console.log('colors[0]: ', colors[0]);
console.log('colors[1]: ', colors[1]);
console.log('colors[2]: ', colors[2]);
console.log('America is', colors[0] + ', ' + colors[1] + ', and ' + colors[2]);
colors[2] = 'green';
console.log('Mexico is', colors[0] + ', ' + colors[1] + ', and ' + colors[2]);
const students = ['Larry', 'Moe', 'Curly', 'Jack'];
const numberOfStudents = students.length;
console.log('Number of students: ', numberOfStudents);
const lastIndex = students.length - 1;
const lastStudent = students[lastIndex];
console.log('Last Student: ', lastStudent);
console.log('Students: ', students);
