console.log('hello, world');
const h1 = document.querySelector('h1');
console.log('h1: ', h1);
console.dir(h1);
const explanation = document.querySelector('#explanation');
console.log('Explaination: ', explanation);
console.dir(explanation);
const hint = document.querySelector('.hint');
console.log('hint: ', hint);
console.dir(hint);
const allPelements = document.querySelectorAll('p');
console.log('All p elements: ', allPelements);
const exampleLink = document.querySelectorAll('.example-link');
console.log('example link: ', exampleLink);
