var width = 40;
var height = 20;
var area = width * height;
console.log('Area: ', area);
console.log('type of area: ', typeof area);
var bill = 50;
var payment = 75;
var change = payment - bill;
console.log('value of change: ', change);
console.log('type of change: ', typeof change);
var quizzes = 80;
var midterm = 75;
var final = 90;
var grade = (quizzes + midterm + final) / 3;
console.log('value of grade: ', grade);
console.log('type of grade: ', typeof grade);
var firstName = 'Barney';
var lastName = 'Rubble';
var fullName = firstName + ' ' + lastName;
console.log('full name: ', fullName);
console.log('type of fullName: ', typeof fullName);
var pH = 5;
var isAcidic = pH < 7;
console.log('value of isAcidic', isAcidic);
console.log('type of isAcidic: ', typeof isAcidic);
var headCount = 300;
var isSparta = headCount === 300;
console.log('value of isSparta: ', isSparta);
console.log('type of isSparta: ', typeof isSparta);
var motto = fullName;
motto += ' is the GOAT';
console.log(motto);
console.log('type of motto: ', typeof motto);
